cd /sources
bash -ex /chroot/man-pages.sh
bash -ex /chroot/tcl.sh
bash -ex /chroot/expect.sh
bash -ex /chroot/dejagnu.sh
bash -ex /chroot/iana-etc.sh
bash -ex /chroot/glibc.sh
bash -ex /chroot/zlib.sh
bash -ex /chroot/bzip2.sh
bash -ex /chroot/xz.sh
bash -ex /chroot/zstd.sh
bash -ex /chroot/file.sh
bash -ex /chroot/readline.sh
bash -ex /chroot/m4.sh
bash -ex /chroot/bc.sh
bash -ex /chroot/flex.sh
bash -ex /chroot/binutils.sh
bash -ex /chroot/gmp.sh
bash -ex /chroot/mpfr.sh
bash -ex /chroot/mpc.sh
bash -ex /chroot/attr.sh
bash -ex /chroot/acl.sh
bash -ex /chroot/libcap.sh
bash -ex /chroot/shadow.sh
bash -ex /chroot/gcc.sh
bash -ex /chroot/pkg-config.sh
bash -ex /chroot/ncurses.sh
bash -ex /chroot/sed.sh
bash -ex /chroot/psmisc.sh
bash -ex /chroot/gettext.sh
bash -ex /chroot/bison.sh
bash -ex /chroot/grep.sh
bash -ex /chroot/bash.sh
bash -ex /chroot/libtool.sh
bash -ex /chroot/gdbm.sh
bash -ex /chroot/gperf.sh
bash -ex /chroot/expat.sh
bash -ex /chroot/inetutil.sh
bash -ex /chroot/perl.sh
bash -ex /chroot/xml-parser.sh
bash -ex /chroot/intltools.sh
bash -ex /chroot/autoconf.sh
bash -ex /chroot/automake.sh
bash -ex /chroot/kmod.sh
bash -ex /chroot/libelf.sh
bash -ex /chroot/libffi.sh
bash -ex /chroot/openssl.sh
bash -ex /chroot/python.sh
bash -ex /chroot/ninja.sh
bash -ex /chroot/meson.sh
bash -ex /chroot/coreutils.sh
bash -ex /chroot/check.sh
bash -ex /chroot/diffutils.sh
bash -ex /chroot/gawk.sh
bash -ex /chroot/findutils.sh
bash -ex /chroot/groff.sh
bash -ex /chroot/grub.sh
bash -ex /chroot/less.sh
bash -ex /chroot/gzip.sh
bash -ex /chroot/iproute2.sh
bash -ex /chroot/kbd.sh
bash -ex /chroot/libpipeline.sh
bash -ex /chroot/make.sh
bash -ex /chroot/patch.sh
bash -ex /chroot/man-db.sh
bash -ex /chroot/tar.sh
bash -ex /chroot/texinfo.sh
bash -ex /chroot/vim.sh
bash -ex /chroot/systemd.sh
bash -ex /chroot/dbus.sh
bash -ex /chroot/pcorps-ng.sh
bash -ex /chroot/util-linux.sh
bash -ex /chroot/e2fsprogs.sh
bash -ex /chroot/cleanup.sh
