cd /sources
bash -ex /chroot/man-pages.sh
bash -ex /chroot/tcl.sh
bash -ex /chroot/expect.sh
bash -ex /chroot/dejagnu.sh
bash -ex /chroot/iana-etc.sh
bash -ex /chroot/glibc.sh
bash -ex /chroot/zlib.sh
bash -ex /chroot/bzip2.sh
bash -ex /chroot/xz.sh
bash -ex /chroot/zstd.sh
bash -ex /chroot/file.sh
bash -ex /chroot/readline.sh
bash -ex /chroot/m4.sh
bash -ex /chroot/bc.sh
bash -ex /chroot/flex.sh
bash -ex /chroot/binutils.sh
bash -ex /chroot/gmp.sh
bash -ex /chroot/mpfr.sh
bash -ex /chroot/mpc.sh
bash -ex /chroot/attr.sh
bash -ex /chroot/acl.sh
bash -ex /chroot/libcap.sh
bash -ex /chroot/shadow.sh
bash -ex /chroot/gcc.sh
bash -ex /chroot/pkg-config.sh
bash -ex /chroot/ncurses.sh
bash -ex /chroot/sed.sh
bash -ex /chroot/psmisc.sh
bash -ex /chroot/gettext.sh
bash -ex /chroot/bison.sh
bash -ex /chroot/grep.sh
bash -ex /chroot/bash.sh
bash -ex /chroot/libtool.sh
bash -ex /chroot/gdbm.sh
bash -ex /chroot/gperf.sh
bash -ex /chroot/expat.sh
bash -ex /chroot/inetutils.sh
bash -ex /chroot/perl.sh
bash -ex /chroot/xml-parser.sh
bash -ex /chroot/intltools.sh
bash -ex /chroot/autoconf.sh
bash -ex /chroot/automake.sh
bash -ex /chroot/kmod.sh
bash -ex /chroot/libelf.sh
bash -ex /chroot/libffi.sh
bash -ex /chroot/cleanup.sh