cd $LFS/sources
bash /scripts/chapter-06/m4.sh
bash /scripts/chapter-06/ncurses.sh
bash /scripts/chapter-06/bash.sh
bash /scripts/chapter-06/coreutils.sh
bash /scripts/chapter-06/diffutils.sh
bash /scripts/chapter-06/file.sh
bash /scripts/chapter-06/findutils.sh
bash /scripts/chapter-06/gawk.sh
bash /scripts/chapter-06/grep.sh